name: Feature Request
description: Suggest an idea for FreshRSS
type: Feature
title: "[Feature] "
labels: ["Feature Request"]
body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: "A clear and concise description of what the problem is. Ex. I’m always frustrated when […]"
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: "A clear and concise description how you work with FreshRSS. Please support with examples."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you’d like
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you’ve considered
      description: "A clear and concise description of any alternative solutions or features you’ve considered."
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
